Repository material-table-core/core, pull requests merged in 2021-05, with the labels that each got.

#193 Remove fade
  src/components/Overlay/OverlayError.js
  src/components/Overlay/OverlayLoading.js
Labels: bug, long-term

#192 added option to choose sort order on column switch between keep same order or reset to asc…
  src/components/MTableHeader/index.js
  src/defaults/props.options.js
  src/material-table.js
  src/prop-types.js
  types/index.d.ts
Labels: enhancement, good first issue, waiting-on-contributor

#180 fix #122
  __tests__/demo/demo-components/RemoteData/index.js
  __tests__/demo/demo.js
  src/material-table.js
Labels: bug, question, waiting-on-contributor

#202 adding props for detail panel offset right and left
  src/components/m-table-body-row.js
  src/defaults/props.options.js
  types/index.d.ts
Labels: enhancement, good first issue

#212 Prop mutation removal
  CHANGELOG.md
  package-lock.json
  package.json
  src/utils/data-manager.js
Labels: bug, documentation, has-urgency
