Repository material-table-core/core, pull requests merged in 2021-01, with the labels that each got.

#33 converted MTableFilterRow class component to functional component
  src/components/MTableFilterRow/BooleanFilter.js
  src/components/MTableFilterRow/DateFilter.js
  src/components/MTableFilterRow/DefaultFilter.js
  src/components/MTableFilterRow/Filter.js
  src/components/MTableFilterRow/LookupFilter.js
  src/components/MTableFilterRow/index.js
  src/components/MTableFilterRow/utils.js
  src/components/index.js
  src/components/m-table-filter-row.js
Labels: in-progress, refactor

#43 converted MTableActions class component to functional component
  src/components/MTableActions/index.js
  src/components/index.js
  src/components/m-table-actions.js
Labels: in-progress, refactor

#42 converted MTableAction class component to functional component
  src/components/m-table-action.js
Labels: in-progress, refactor

#29 converted MTableCell class component to functional component
  src/components/m-table-cell.js
Labels: in-progress, refactor

#30 converted MTableEditCell class component to functional component
  src/components/m-table-edit-cell.js
Labels: in-progress, refactor

#31 converted MTableEditField class component to functional component
  src/components/m-table-edit-field.js
Labels: in-progress, refactor

#32 converted MTableEditRow class component to functional component
  src/components/m-table-edit-row.js
Labels: in-progress, refactor

#35 converted MTableGroupRow class component to functional component
  src/components/m-table-group-row.js
Labels: in-progress, refactor

#41 converted MTableToolbar class component to functional component
  src/components/m-table-toolbar.js
Labels: in-progress, refactor

#36 Refactor m table groupbar class to functional component
  src/components/m-table-groupbar.js
Labels: in-progress, refactor

#40 converted MTableSteppedPagination class component to functional compo…
  src/components/m-table-stepped-pagination.js
Labels: in-progress, refactor

#38 converted MTablePaginationInner class component to functional component
  src/components/m-table-pagination.js
Labels: in-progress, refactor

#37 converted MTableHeader class component to functional component
  src/components/m-table-header.js
Labels: in-progress, refactor

#53 Fix import in BooleanFilter.js
  src/components/MTableFilterRow/BooleanFilter.js
Labels: question, waiting-on-contributor

#62 Prevent loss of sorting state
  src/material-table.js
Labels: bug, has-urgency
